name: Build

on: [push, pull_request]

jobs:
  build:
    name: Windows (x64)
    runs-on: windows-latest
            
    steps:
    - name: Install dependencies
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Install cmake
      if: steps.cache-dep.outputs.cache-hit != 'true'
      uses: jwlawson/actions-setup-cmake@v1.12

    - name: Set MSVC environment
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: x64
        
    - name: Build
      shell: cmd
      run: Build.bat
