name: Build

on:
  pull_request:
    branches: [main]
    
jobs:
  build:
    name: Windows (x64)
    runs-on: windows-latest
            
    steps:
    - name: Install dependencies
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

